name: check-code
on:
  push:
    paths-ignore:
      - '**.md'
      - 'website/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - 'website/**'

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on

    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: vet
        run: make vet

      - name: static
        run: make static

      - name: test
        run: make test

      - name: tags
        run: make tagverify
